<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var common\models\profile\Profile $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="profile-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Profile',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'id')->textInput() ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'event_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\event\Event::find()->all(), 'id', 'id'),
    ['prompt' => 'Select']
); ?>
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'age')->textInput() ?>
			<?=                         $form->field($model, 'gender')->dropDownList(
                            common\models\profile\Profile::optsgender()
                        ); ?>
			<?= $form->field($model, 'height')->textInput() ?>
			<?= $form->field($model, 'dress')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'appearance')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'created_at')->textInput() ?>
			<?= $form->field($model, 'updated_at')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Profile',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

