<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\location\base;

use Yii;

/**
 * This is the base-model class for table "location_provider".
 *
 * @property integer $id
 * @property string $identity_kind
 * @property string $identity_info
 * @property string $latitude
 * @property string $longitude
 * @property string $provided_at
 * @property string $created_at
 *
 * @property \common\models\location\LocationNew[] $locationNews
 */
abstract class LocationProvider extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const IDENTITY_KIND_POLICE = 'police';
    const IDENTITY_KIND_MONITOR_SYSTEM = 'monitor_system';
    const IDENTITY_KIND_PEOPLE = 'people';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_provider';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['identity_kind'], 'string'],
            [['identity_info'], 'required'],
            [['latitude', 'longitude'], 'number'],
            [['provided_at', 'created_at'], 'safe'],
            [['identity_info'], 'string', 'max' => 255],
            [['identity_info'], 'unique'],
            ['identity_kind', 'in', 'range' => [
                    self::IDENTITY_KIND_POLICE,
                    self::IDENTITY_KIND_MONITOR_SYSTEM,
                    self::IDENTITY_KIND_PEOPLE,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'identity_kind' => 'Identity Kind',
            'identity_info' => 'Identity Info',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'provided_at' => 'Provided At',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationNews()
    {
        return $this->hasMany(\common\models\location\LocationNew::className(), ['provider_id' => 'id']);
    }




    /**
     * get column identity_kind enum value label
     * @param string $value
     * @return string
     */
    public static function getIdentityKindValueLabel($value){
        $labels = self::optsIdentityKind();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column identity_kind ENUM value labels
     * @return array
     */
    public static function optsIdentityKind()
    {
        return [
            self::IDENTITY_KIND_POLICE => 'Police',
            self::IDENTITY_KIND_MONITOR_SYSTEM => 'Monitor System',
            self::IDENTITY_KIND_PEOPLE => 'People',
        ];
    }

}
