<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\message\base;

use Yii;

/**
 * This is the base-model class for table "message_record".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $number
 * @property integer $event_id
 * @property string $created_at
 *
 * @property \common\models\event\Event $event
 * @property \common\models\User $user
 */
abstract class MessageRecord extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message_record';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'number', 'event_id'], 'required'],
            [['user_id', 'event_id'], 'integer'],
            [['created_at'], 'safe'],
            [['number'], 'string', 'length' => 11],
            [['number', 'event_id'], 'unique', 'targetAttribute' => ['number', 'event_id'], 'message' => 'The combination of Number and Event ID has already been taken.']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'number' => 'Number',
            'event_id' => 'Event ID',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\event\Event::className(), ['id' => 'event_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }




}
